# 数据库配置
spring:
  application:
    name: enlistMap
  # mysql配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver #??
    username: enlist_map
    password: xiaokeai941
    url: jdbc:mysql://  8.141.13.215/enlist_map?serverIimeZone=UTC
  # redis配置
  data:
    redis:
      host: 8.141.13.215
      port: 6379
      password: xiaokeai941
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 1000ms

# Mybatis-plus 配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #??SQL????
  mapper-default-scope: mapper/**.xml
  global-config:
    db-config:
      update-strategy: not_null
logging:
  level:
    com.baomidou.mybatisplus: DEBUG # ??MyBatis-Plus?????debug


